---
- name: Download the helm archive.
  get_url:
    url: "{{ helm_download_url }}"
    dest: /tmp
    checksum: sha256:{{ helm_checksum_url }}
    mode: 0755
  register: helm_download

- name: Unarchive the helm archive.
  unarchive:
    src: "{{ helm_download.dest }}"
    dest: /tmp
    mode: 0755
    remote_src: true
    extra_opts: [--strip-components=1]

- name: Copy the helm binary into place.
  copy:
    src: /tmp/helm
    dest: "{{ helm_bin_path }}"
    mode: 0755
    remote_src: true
  become: true
