---
- name: Check the presence of the helm binary.
  stat:
    path: "{{ helm_bin_path }}"
  register: helm_check

- name: Check the helm version.
  shell: "{{ helm_bin_path }} version --template='{{ '{{' }} .Version {{ '}}' }}'"
  failed_when: false
  changed_when: false
  register: helm_current_version

- name: Install helm v{{ helm_version }}
  include_tasks: install.yml
  when: >-
    not helm_check.stat.exists
    or helm_version not in helm_current_version.stdout
